extract:
  test_samples: 200
  train_samples: 316

prepare:
  co_relation_threshold: .4

train:
  fit_intercept: True
  normalize: False
  n_jobs: 2
  copy_X: True

evaluate:
  # All metrics are available
  # "rsquare","mse","rmse","mae"
  metrics: "rsquare, mse, rmse, mae"
